### ISSUE TITLE
Synology solution

### ISSUE THREAD

**Issue by cirrusflyer** [ahaenggli/AzureAD-LDAP-wrapper#11]
Apologies if this isn't a smart question - but can you explain what this solution does that's different than this:

https://kb.synology.com/en-my/DSM/tutorial/How_to_join_NAS_to_Azure_AD_Domain

Thanks

**Comment by ahaenggli** [comment]
My wrapper creates an entire ldap server. So you can use it with several 3rd party (legacy) software in the same network.
It uses the AzureAD Service (which is available for free).

Your link describes how to join just your Synology-NAS to the Azure AD Domain Service. It will be hard to use this in (old) 3rd party (legacy) software. You'll also need to pay for the Domain Services in Azure to use this.

**Comment by cirrusflyer** [comment]
Thanks!  So if I already have Azure AD Premium P1 adn don't need support for older software, the Synology solution would work fine?

**Comment by ahaenggli** [comment]
Yes, the Synology solution should work fine in your case :)
