### ISSUE TITLE
Not all users returned

### ISSUE THREAD

**Issue by paulwfield** [ahaenggli/AzureAD-LDAP-wrapper#14]
**Describe the bug**
Only the first 46 users are being returned

**To Reproduce**
Steps to reproduce the behaviour:
1. Add lots of users in AzureAD
2. connect and browse the LDAP and look for users high in the alphabet 

this is because uri: MS_GRAPH_SCOPE + 'v1.0/users', In a single API call, we are able to get a small list
we can increase by adding ?$top=999 
uri: MS_GRAPH_SCOPE + 'v1.0/users?$top=999',

but if more that 999 it should do pagination with Nextlink 
e.g.
var nextLink = "@odata.nextLink";    

**Expected behaviour**
All users to be returned

**Comment by ahaenggli** [comment]
Thx for reporting! The API v1.0/users should return (at least) 100 user objects (according to the [docu](https://docs.microsoft.com/en-us/graph/api/user-list?view=graph-rest-1.0&tabs=http#optional-query-parameters)). 
But paying attention to pagination is needed for sure.
However, the number 46 is a bit strange. Maybe there are additional limits by the used ldapjs or holding the entries in the memory. I will take a closer look at this.

**Comment by paulwfield** [comment]
Something like
paged: { pageSize: 250 }
https://github.com/ldapjs/node-ldapjs/blob/ad451edc18d7768c3ddee1a1dd472d2bbafdae5e/docs/client.md#search

Then a callback in the on-page event e.g.
ldapresponse.on('page', function(entry, cb) {
  if(cb) cb();
});

**Comment by ahaenggli** [comment]
Your pagesize example is for the ldapjs client. I'm using the server. 
It seems, on server side there is no default limit. So, nothing to change here.
Objects and Strings of several MB are looking also fine in nodejs. 
A handling for `odata.nextLink` wil be added in the next release.
