### ISSUE TITLE
Question / multiple Microsoft 365 organizations

### ISSUE THREAD

**Issue by piokaczo** [ahaenggli/AzureAD-LDAP-wrapper#16]
Hi!

Is there a way of querying multiple Microsoft 365 tenants? I am looking for way to allow M365 users of few independent organizations to show up in in Synology and other LDAP-enabled services (preferably somehow tagged as user of such and such organization).

**Comment by ahaenggli** [comment]
Currently there is no way to query multiple tenants. 
The only possibility would be, if you define a main tenant and connect it. Then the users of the other tenants would have to be added as guests in your main tenant. Afterwards you could create a group for each organization and assign the guest users in it.
