### ISSUE TITLE
MFA possible/planed

### ISSUE THREAD

**Issue by Jokerschatz** [ahaenggli/AzureAD-LDAP-wrapper#17]
**Describe the bug**
I successfully sync the users  local LDAP server / PW Changes were recognized and 
all works perfect. But if I enable MFA on the O365 site for one User this user can't login in anymore.

**Question**
is there any way to use the smooth tool with MFA enabled?

**Comment by CTroessaert** [comment]
Did anyone tried to make a conditional access policy to bypass MFA on specific device or from specific IP?

**Comment by ahaenggli** [comment]
Hi @CTroessaert, I didn't go that far, but I was successful by excluding the whole app in a mfa conditional access policy. You can find a bit more details in issue #35. 

Feel also free to try the new env var `GRAPH_IGNORE_MFA_ERRORS`, available in the docker dev tag. Any test and use is very welcome :)
