### ISSUE TITLE
Support to LDAP queries

### ISSUE THREAD

**Issue by simomuso** [ahaenggli/AzureAD-LDAP-wrapper#18]
Hi! This project is very interesting 👍  
I was wondering if it is possible to query the AzureAD fetched users using LDAP standard queries (with filter support). I could not find such possibility in the documentation.

**Comment by ahaenggli** [comment]
Hi! Yes, that should work.
I'm using [ldapjs](http://ldapjs.org/) to create the server. So you should be able to use all of its possibilities.
Add and Modify should also work (not only search queries). I did some tests in PowerShell which you can find [here](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/blob/main/schema/ldap_tests.ps1).

**Comment by simomuso** [comment]
Hi! I will try to use this strategy, I didn't notice at first.

Thank you for the fast response! :-)
