### ISSUE TITLE
SaveJSONtoFile failed

### ISSUE THREAD

**Issue by JETomi** [ahaenggli/AzureAD-LDAP-wrapper#20]
**Describe the bug**
Maybe not a bug but i'm not sure what to do.
I get these errors in the log. One for every group aswell.
![image](https://user-images.githubusercontent.com/56302309/171359333-85fc47fe-a083-41aa-bd3f-0ec4e537e324.png)
I think it fails to open the file because it failed to save the file?
I don't get this error when not specifing a volume, but then the users aren't saved after restart so they have to relog DSM to use SMB?
![image](https://user-images.githubusercontent.com/56302309/171360154-558b62fa-f811-42d7-8064-b4014a1007ab.png)

**Comment by ahaenggli** [comment]
Thx for reporting! Looks like the permissions are not set as expected... 
I should reset the permissions every time the container is started, not just when the container is created. I'll fix it in the next version.

As a temporary workaround, you could give "everyone" write access to your mapped folder:
![grafik](https://user-images.githubusercontent.com/23347180/171989634-d1eef223-6867-49ef-913c-0a177520f13f.png)

**Comment by ahaenggli** [comment]
fixed with v1.8.0
