### ISSUE TITLE
Partially working; Not the Full GROUP list, but full user list; No local shares access with LDAP credentials over SMB

### ISSUE THREAD

**Issue by ccg-david** [ahaenggli/AzureAD-LDAP-wrapper#21]
Note: DSM 7.1
Followed steps and LDAP connects and grabs the email addresses which, can allow for logging into the DSM via the WEB but no access to Synology resources Locally; 

Also the Groups list ONLY shows Users@domain nothing else

**To Reproduce**
1. Setup and install as instructed
2. When it says that the group name exists, for {users} you have to click Skip; 
3. login to PC and then try to access network resources on that Synology;

**Screenshots**
<img width="909" alt="image" src="https://user-images.githubusercontent.com/100220187/174867342-7d5d43e1-8ddb-448a-ab0b-aaa6375bdb1c.png">

**Comment by ccg-david** [comment]
I am using the latest version. What shows are screenshots that were included in the post. 

date | stream | content
-- | -- | --
2022-06-21T17:19:18.285216872Z | stdout | }
2022-06-21T17:19:18.285174011Z | stdout | path: [32m'./.cache/azure.json'[39m
2022-06-21T17:19:18.285132867Z | stdout | syscall: [32m'open'[39m,
2022-06-21T17:19:18.285090321Z | stdout | code: [32m'EACCES'[39m,
2022-06-21T17:19:18.285042480Z | stdout | errno: [33m-13[39m,
2022-06-21T17:19:18.284972520Z | stdout | ERROR: 2022-06-21T17:19:18.284Z:  helper.js [Error: EACCES: permission denied, open './.cache/azure.json'] {
2022-06-21T17:19:18.284503678Z | stdout | ERROR: 2022-06-21T17:19:18.284Z:  helper.js error in SaveJSONtoFile for file ./.cache/azure.json
2022-06-21T17:19:18.284411257Z | stdout | }
2022-06-21T17:19:18.284367030Z | stdout | path: [32m'./.cache/users.json'[39m
2022-06-21T17:19:18.284324890Z | stdout | syscall: [32m'open'[39m,
2022-06-21T17:19:18.284278900Z | stdout | code: [32m'EACCES'[39m,
2022-06-21T17:19:18.284233100Z | stdout | errno: [33m-13[39m,
2022-06-21T17:19:18.284170708Z | stdout | ERROR: 2022-06-21T17:19:18.283Z:  helper.js [Error: EACCES: permission denied, open './.cache/users.json'] {
2022-06-21T17:19:18.283807066Z | stdout | ERROR: 2022-06-21T17:19:18.283Z:  helper.js error in SaveJSONtoFile for file ./.cache/users.json


There are errors that i see in the logs. 
Also I only have users@domain in the Group section not the actual groups;

**Comment by ccg-david** [comment]
I just removed the PATH from the variables to test;

**Comment by ahaenggli** [comment]
Looks like the same problem as in #20. Could you try the workaround from [here](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/issues/20#issuecomment-1146558980)?

If you removed the PATH variable from the docker container, please add it again.

**Comment by ahaenggli** [comment]
Given the error 400, it looks like a wrong value in the env var `GRAPH_FILTER_GROUPS`. By default it should be empty (or space).
Microsoft allows only [these](https://docs.microsoft.com/en-us/graph/api/resources/group?view=graph-rest-1.0#properties) properties for the group filter.

**Comment by ccg-david** [comment]
So now the only thing missing, is SMB access to the files on the Synology using the Credentials that are cached from LDAP-wrapper

Evening after using the Azure credentials on the DSM login, 
When I browse to the network and it asks for a login, it just repeats asking for log on with no errors presented on Windows Side of things

**Comment by ccg-david** [comment]
Last time i joined it a few different ways, both with existing and non-existing with and without admin privileges; 

I removed the LDAP_BINDUSER env var as it was optional. 

What should i be using an existing or non-existing?

**Comment by ahaenggli** [comment]
Any of your AzureAD users can bind (and log in) to this LDAP server from your network, send queries to the server and even retrieve entries. So, for security reasons, users that exist in AAD cannot see or change the hashed passwords of other users.
You can use `LDAP_BINDUSER` to add additional - not in AzureAD existing - users. Format: `any-random-username|password`. But you can also add an existing user there. These users have full read permissions and can also see the sambaNTPassword hash. 
SMB is like a "man in the middle". Windows sends hashed passwords to SMB, SMB gets the hashes from the wrapper, SMB compares the hashes and grants access or not. I would recommend using a non-existent user so you don't have to rejoin your NAS if the password of your existing user is changed.

**Comment by ccg-david** [comment]
I understand the LDAP_BINDUSER with that explanation. And it's now working as intended.

**Comment by ccg-david** [comment]
Yes I am using the latest Version. The Screen Shots were the ones that
were autofilled into the Post.

For simplicity sake, I could give you login credentials for the Synology in
Question or if you rather have the logs, I can get those too.

Regards,

David Wright Jr.

*Computer Technician, Computer Consultants Group*

o: *8437227607 ext. 4 *

s: https://ccgnet.com e: ***@***.***
