### ISSUE TITLE
2FA account cannot login to DSM after sync

### ISSUE THREAD

**Issue by ccg-david** [ahaenggli/AzureAD-LDAP-wrapper#22]
I know I have the correct Username Password as I can login to the Computer; 

I enabled 2FA on a test account and even copied the app password for it; 
I've tried both the App Password and the known correct Password and it fails to auth/login to the DSM on the Web and thereby no SMB access; 

  detail: AuthenticationRequiredError: invalid_grant: AADSTS50076: Due to a configuration change made by your administrator, or because you moved to a new location, you must use multi-factor authentication to access '00000003-0000-0000-c000-000000000000'.

ERROR: 2022-06-28T14:24:06.991Z:  server.js server.bind testing@XXXX.com wrong password, retry against sambaNTPassword

**Comment by ahaenggli** [comment]
MFA is not supported, the explanations from Microsoft are linked the FAQ.
