### ISSUE TITLE
Unable to set 389 port redirection in docker container on DSM 7.1-42661

### ISSUE THREAD

**Issue by skarpukhin** [ahaenggli/AzureAD-LDAP-wrapper#25]
**Describe the bug**
Could not correctly setup AzureAD-LDAP-wrapper  in docker container on DSM 7.1-42661 - unable to set 389 port redirection

**To Reproduce**
According to the manual, while creating new docker container user should set port redirection from 13389 to 389, but this ends up with a following error (Local port conflicts with other ports used by other services)
![image](https://user-images.githubusercontent.com/89646305/178055005-1a78dac6-abef-4ea6-b631-a4ee54ab9364.png)

One could change target port to something else (like 3389) while creating container and try to change port to 389 after container have been created, but this also leads to error and couldn't be completed
![image](https://user-images.githubusercontent.com/89646305/178055676-19c78fef-d0d4-46b7-908a-41cc45200bbc.png)

As a result, LDAP client in Synology cannot locate LDAP server in docker container, because only non-standart port for LDAP could be used
![image](https://user-images.githubusercontent.com/89646305/178055925-3e3e1acb-9e90-4b13-8f7e-8bc11b692220.png)

**Comment by skarpukhin** [comment]
Is there any way to force port redirection to 389 or to set non-standard port for LDAP-Client in Synology DSM?

**Comment by skarpukhin** [comment]
Exporting container configuration, manually editing port to 389 in JSON and importing it back didn't help either,

Synology Docker changes port from 389 to auto while importing configuration back :(

![image](https://user-images.githubusercontent.com/89646305/178057543-376e2531-8c2d-4807-a769-fe3fb5d73e92.png)

**Comment by skarpukhin** [comment]
Thank you very much, deleting Synology LDAP Server did help to resolve this issue!

**Comment by skarpukhin** [comment]
Could I ask one more side question here?

I'm trying now to connect to my containerized LDAP server, 

Do I correctly understand that LDAP Administrator account here could only from LDAP_BINDUSER variable? I've tried to use here any accounts from my AAD with administrative priveleges, but without success

![image](https://user-images.githubusercontent.com/89646305/178063209-87e68cd3-e44d-4cfc-9ce4-5da73decf048.png)

**Comment by ahaenggli** [comment]
That's correct.
