### ISSUE TITLE
No groups in groups.json

### ISSUE THREAD

**Issue by marc-odp** [ahaenggli/AzureAD-LDAP-wrapper#28]
Hi, 
I try to install the LDAP wrapper but I have a few problems.
The first one :

> For type Application allow User.Read.All and Group.Read.All.
> For type Delegated allow User.Read.

I did this, but my _groups.json_ is empty... 
[]
And I see complaints in the log...  _ldapwrapper.js no group found for user uid=_ ...

(_azure.json_ and _users.json_ are ok.)
Any idea ?

-marc-

**Comment by ahaenggli** [comment]
Could you try changing the environment variable `GRAPH_FILTER_GROUPS` to nothing? (or put a space or remove the whole environment variable)
In the latest version the default filter for groups is set to security groups, I suppose you are using a different type of group.

**Comment by marc-odp** [comment]
Removing `GRAPH_FILTER_GROUPS` did it.
I am using MS Teams, so my groups are Teams groups.
Thank you !
