### ISSUE TITLE
Trying to connect with Jxplorer

### ISSUE THREAD

**Issue by marc-odp** [ahaenggli/AzureAD-LDAP-wrapper#29]
II think I did all the setup for the ldap server (using a docker container and Synology NAS) but I cannot manage to connect to it using Jxplorer or anything else. I didn't do the part for configuring Samba or to make the NAS as a client because I don't plan to use the ldap server like that. My plan is to use it with [piserver](https://github.com/raspberrypi/piserver).
What settings could I try ?

<img width="383" alt="image" src="https://user-images.githubusercontent.com/17361839/187448032-8e239fab-aa71-4e53-9656-c68ab682c812.png">

<img width="358" alt="image" src="https://user-images.githubusercontent.com/17361839/187447824-9322ca9b-2b80-4995-bd25-0aa5a9976636.png">

<img width="336" alt="image" src="https://user-images.githubusercontent.com/17361839/187447442-07ab5ed9-b411-46ab-919a-59dae3dfa5e6.png">

**Comment by ahaenggli** [comment]
Is it possible that a firewall is blocking the port? If not, it may be that ldapseach is not considered a valid user DN by Jxplorer and prefixes it with a different value. Could you try "uid=ldapsearch" or "uid=ldapsearch,cn=users,dc=example,dc=com" instead?

**Comment by marc-odp** [comment]
Thank you. It works
