### ISSUE TITLE
unable to bind to 127.0.0.1

### ISSUE THREAD

**Issue by q20** [ahaenggli/AzureAD-LDAP-wrapper#3]
Hey there!

Thanks for putting together something Synolgy really should be offering out of the box.
I've got a little experience with Docker and AD, so I thought this would take no time to set up. Unfortunately, though, I'm getting stuck trying to bind.

Here are the relevant environment variables:
<img width="590" alt="image" src="https://user-images.githubusercontent.com/17024596/114855423-3e686500-9de6-11eb-83ae-948b032d6acb.png">

The Synology correctly identifies your LDAP service:
<img width="526" alt="image" src="https://user-images.githubusercontent.com/17024596/114855538-5dff8d80-9de6-11eb-9ecf-8aac0b994f0b.png">

When hitting apply and entering the bind DN and password as follows:
uid=ldapsearch,cn=users,dc=example,dc=com
*password*

...then hit Apply:
<img width="648" alt="image" src="https://user-images.githubusercontent.com/17024596/114855853-adde5480-9de6-11eb-8ca6-d6cf3e685296.png">

I see the following error:
<img width="652" alt="image" src="https://user-images.githubusercontent.com/17024596/114855974-cf3f4080-9de6-11eb-998c-4dabfce0d246.png">

Any idea? I have tried this multiple times, without success.

Help would be greatly appreciated.
Thanks! :D

**Comment by ahaenggli** [comment]
hi,
the first thing you could try is using just the name (without uid=,...) 
![grafik](https://user-images.githubusercontent.com/23347180/114859236-c2245080-9dea-11eb-81a1-d602beda9a5b.png)

Is it still the same error containing "operation failed"?
If so, what if you type in a wrong password - does it still say "operation failed" or is it "wrong credentials"?

Are there any errors or messages in the logs of your docker container?

**Comment by q20** [comment]
Thanks for the super-fast response! :D

I'm now trying without the full DN.
Here's the result with an incorrect password:
<img width="641" alt="image" src="https://user-images.githubusercontent.com/17024596/114862421-cfdbd500-9dee-11eb-8a37-18682e53c76b.png">

Correct password:
<img width="638" alt="image" src="https://user-images.githubusercontent.com/17024596/114863207-bd15d000-9def-11eb-922d-01a6fdee58be.png">

**Comment by ahaenggli** [comment]
ok, that's great - the binding seems to work and the initial search fails...
is there anything in your log?
![grafik](https://user-images.githubusercontent.com/23347180/114864713-9bb5e380-9df1-11eb-9138-5213537b7a3b.png)

if not - can you set the env var `LDAP_DEBUG` to `true`:
![grafik](https://user-images.githubusercontent.com/23347180/114864513-5ee9ec80-9df1-11eb-90c0-48a29365550e.png)
restart your container, try to bind again and check the log

**Comment by q20** [comment]
Here we go. Debug logging enabled, user/pass correct:
<img width="643" alt="image" src="https://user-images.githubusercontent.com/17024596/114866310-ad988600-9df3-11eb-9ead-7f1c43eab922.png">


INFO: 2021-04-15T12:04:29.981Z:  server.js server.search Search for => DB: dc=example,dc=com; Scope: sub; Filter: (&(objectclass=posixaccount)(uid=ldapsearch)); Attributes: ;
ERROR: 2021-04-15T12:04:29.985Z:  server.js server.search Error [InvalidDistinguishedNameError]: _DELETED_
    at invalidDN (/app/node_modules/ldapjs/lib/dn.js:8:13)
    at parseRdn (/app/node_modules/ldapjs/lib/dn.js:173:54)
    at parse (/app/node_modules/ldapjs/lib/dn.js:294:17)
    at DN.dnEquals [as equals] (/app/node_modules/ldapjs/lib/dn.js:400:40)
    at scopeCheck (/app/server.js:234:36)
    at Server.<anonymous> (/app/server.js:242:18)
    at messageIIFE (/app/node_modules/ldapjs/lib/server.js:405:63)
    at Parser.<anonymous> (/app/node_modules/ldapjs/lib/server.js:415:8)
    at Parser.emit (events.js:315:20)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:107:8)


I deleted the InvalidDistinguishedNameError UID mentioned, as it's a valid Azure AD user and email address.

**Comment by q20** [comment]
Just tried again and got the following:


INFO: 2021-04-15T12:29:02.586Z:  server.js server.bind uid=ldapsearch,cn=users,dc=example,dc=com
INFO: 2021-04-15T12:29:02.586Z:  server.js server.bind ldapsearch binduser, **_you shall pass_**
INFO: 2021-04-15T12:29:02.587Z:  server.js server.search Search for => DB: dc=example,dc=com; Scope: sub; Filter: (objectclass=posixaccount); Attributes: dn,cn,uid,gecos,shadowexpire,mail,pwdaccountlockedtime,pwdchangedtime,pwdreset,pwdpolicysubentry;
ERROR: 2021-04-15T12:29:02.590Z:  server.js server.search Error [InvalidDistinguishedNameError]: DELETED
    at invalidDN (/app/node_modules/ldapjs/lib/dn.js:8:13)
    at parseRdn (/app/node_modules/ldapjs/lib/dn.js:173:54)
    at parse (/app/node_modules/ldapjs/lib/dn.js:294:17)
    at DN.dnEquals [as equals] (/app/node_modules/ldapjs/lib/dn.js:400:40)
    at scopeCheck (/app/server.js:234:36)
    at Server.<anonymous> (/app/server.js:242:18)
    at messageIIFE (/app/node_modules/ldapjs/lib/server.js:405:63)
    at Parser.<anonymous> (/app/node_modules/ldapjs/lib/server.js:415:8)
    at Parser.emit (events.js:315:20)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:107:8)
INFO: 2021-04-15T12:30:02.598Z:  server.js server.search Search for => DB: dc=example,dc=com; Scope: sub; Filter: (&(objectclass=posixaccount)(uid=ldapsearch)); Attributes: ;
ERROR: 2021-04-15T12:30:02.600Z:  server.js server.search Error [InvalidDistinguishedNameError]: DELETED
    at invalidDN (/app/node_modules/ldapjs/lib/dn.js:8:13)
    at parseRdn (/app/node_modules/ldapjs/lib/dn.js:173:54)
    at parse (/app/node_modules/ldapjs/lib/dn.js:294:17)
    at DN.dnEquals [as equals] (/app/node_modules/ldapjs/lib/dn.js:400:40)
    at scopeCheck (/app/server.js:234:36)
    at Server.<anonymous> (/app/server.js:242:18)
    at messageIIFE (/app/node_modules/ldapjs/lib/server.js:405:63)
    at Parser.<anonymous> (/app/node_modules/ldapjs/lib/server.js:415:8)
    at Parser.emit (events.js:315:20)
    at Parser.write (/app/node_modules/ldapjs/lib/messages/parser.js:107:8)

Interesting that on bind it throws an error regarding the same Azure AD user.

**Comment by q20** [comment]
It's actually even stranger than that. The invalid distinguished name is a combination of three firstnames:

ERROR: 2021-04-15T12:29:02.590Z:  server.js server.search Error [InvalidDistinguishedNameError]: cn=FIRSTNAME1,FIRSTNAME2,FIRSTNAME3,cn=groups,dc=DOMAIN,dc=COM

**Comment by ahaenggli** [comment]
Thx! the problem is the mentioned group called "FIRSTNAME1,FIRSTNAME2,FIRSTNAME3". 
The underlying ldapjs doesn't like commas or equal-symbols in names. I'll remove those chars in group names in the next version of the wrapper.

Could you rename the group in your [azuread](https://aad.portal.azure.com/#blade/Microsoft_AAD_IAM/GroupsManagementMenuBlade/AllGroups)?

**Comment by q20** [comment]
Arg, unfortunately I cannot rename the group - it's linked to an Office 365 group and Team. I fear renaming it in Azure will wreak havoc. Bummer.
Any other suggestions?

**Comment by ahaenggli** [comment]
wait a few hours...
I try to change the internal used group name (entryDN) for the ldap-server-cache:
- replace accents (ç,è,ö, etc.) with the latin alternatives (c,e,o, etc.)
- remove non alpha-numeric chars with dashes

... while keeping the "original" name for display (CN)

**Comment by q20** [comment]
You're a champ! :D

**Comment by ahaenggli** [comment]
V1.2.0 should now be in the latest docker image.
I hope it works for you too!

**Comment by q20** [comment]
BINGO!
<img width="458" alt="image" src="https://user-images.githubusercontent.com/17024596/114921883-52828580-9e2b-11eb-92cb-6e4d28baf132.png">

Have a few coffees on me.  ; )

**Comment by ahaenggli** [comment]
thx! :)

(don't forget to set `LDAP_DEBUG` back to `false`)

**Comment by q20** [comment]
One step ahead of you there.  ; )
