### ISSUE TITLE
LDAP_PORT can be changed ?

### ISSUE THREAD

**Issue by marc-odp** [ahaenggli/AzureAD-LDAP-wrapper#30]
I don't see reference to LDAP_PORT in the documentation.
That value can be changed or we have to absolutely use 13389 ?
Thanks.

**Comment by marc-odp** [comment]
I don't want to use Docker in Bridge mode but in MACVLAN mode. So using the port 389 directly... No port mapping.

**Comment by ahaenggli** [comment]
It is not yet a feature, so LDAP_PORT is not included in the documentation. The application inside the container does not run as root, so it can only bind ports larger than 1024. So, yes you could already change the port, but not to the one you want.

Theoretically, I would "only" have to set cap_net_bind_service additionally when setting up in the image... I will try it out in the next few days/weeks.

**Comment by marc-odp** [comment]
I understand now why I could not access port 369. 
I was thinking to use MACVLAN mode because the host is already using 369, so I have a conflict with the container in BRIDGE mode.
When you come with a new version, I will be happy to try it. Thanks !

**Comment by ahaenggli** [comment]
The version in the dev tag should now also be able to use the lower ports without errors. It would be great if you could try it out, too :)

**Comment by marc-odp** [comment]
I just tried it an it works fine with port 389 and MACVLAN. Great, thank you !
