### ISSUE TITLE
User authentification cache persistance

### ISSUE THREAD

**Issue by skarpukhin** [ahaenggli/AzureAD-LDAP-wrapper#33]
**Describe the bug**
user authentication cache is deleted when Synology NAS itself is restarted (for example for updates or technical maintenance)

**To Reproduce**
1. Shutdown Synology
2. Power-on Synology
3. Try to access SMB share with previously used LDAP credentials

**Expected behavior**
Access to SMB with previously "activated" LDAP credentials (via Web-GUI) should persist between docker image or synology nas restarts.

**Additional context**
I have used volume mapping in docker configuration to make LDAP files visible outside of docker image. I suppose, that these files should persist between docker image restarts and whole Synology NAS restarts. In my environment users access synology NAS web-DSM and SMB through VPN tunnel (which also relies on LDAP user authentification). When cached credentials disappear my users can't do anything because they cannot reactivate LDAP credentials via Web-DSM, due to VPN tunnel also beinng non-functional

May be it is possible to add one more environment variable to make LDAP files really persistent and keep them from being deleted?

**Comment by ahaenggli** [comment]
The desired behavior should work by default if the correct volume is mapped. Which volume have you mapped exactly? The file "azure.json" should be rewritten every 30 minutes. Is that also the case or does simply "nothing" happen to the file's modification date after a container/NAS reboot? 
Within the file, the values for "sambaNTPassword" should be maintained each time. If you manually restart the container, do you possibly have only XXXXXX in the azure.json file for the attribute "sambaNTPassword" or still the old values? 
Do you have an error message in the log of the container? (e.g. the same as in issue #20?)

**Comment by skarpukhin** [comment]
Hello, sorry for late reply!

When I restart docker containter, azure.json doesn't change, but when i restarted whole synology box, all LDAP files (azure.json, users.json, groups.json and so on) was rewritten, and my cached passwords dissapeared

**Comment by skarpukhin** [comment]
![image](https://user-images.githubusercontent.com/89646305/189944614-6639f079-b1ed-4768-aea4-0bcbce6fbbd1.png)

There was no errors related to persistent storage while rebooting (only errors connected to some of my users, which doesn't belong to any group)

**Comment by ahaenggli** [comment]
I can't reproduce that on my own setup yet. 

- If you put another file like "readme.txt" in the same directory as the azure.json. Does the readme file disappear after a NAS reboot?
- The file "azure.json" should be rewritten every 30 minutes while the container is running. Is this also the case for you when you check the modification date from time to time during a day?
![grafik](https://user-images.githubusercontent.com/23347180/190010823-a79e453f-9740-42d1-a8f0-41893147acbe.png)
- Do you have only "XXXX" for "sambaNTPassword" (cached credentials) in the "azure.json" file or any other values after a user login was successful?
- What are the values for "sambaNTPassword" after a restart? Only XXXXX or still the cached credentials?
- Can you reproduce the behaviour by reset the stopped container?
![grafik](https://user-images.githubusercontent.com/23347180/190014238-7cabc4e4-a713-42ac-a1ba-5a02aa148ad3.png)
- Could you export your container settings, anonymise all personal data (Azure tokens, domains, binduser, ...) and upload the file in this issue?
![grafik](https://user-images.githubusercontent.com/23347180/190014139-f3febece-5c41-4235-ae69-9c3aa667fca8.png)

**Comment by skarpukhin** [comment]
I've rechecked everything one time more after clean AzureAD-LDAP-wrapper docker container reinstall and could state following:

0. No more I could reproduce that cached SambaNTPassword disappears from Azure.json for users, previously checked-in via web-gui;
1. Timestamps of all  *.json files in mapped folder change once in 30 minutes (or less, or more, according to docker container LDAP_SYNC_TIME config value), and after docker container or NAS restart - nothing unexpected here;
2. Contents of all *.json files don't change (if no changes happened in user db in azure backend) when files are updated by LDAP_SYBC_TIME timer or when docker restarts or when whole NAS restarts;
3. Any additional files e.g. readme.txt placed next to mapped *.json files don't change, nor their timestamps change.

So, to finalize: original issue couldn't be verified, I'm really sorry for any inconvenience, and spent time and efforts from your side.

However one "glitch" is still present. After Synology box 'cold' restart user with cached credentials couldn't access mapped folders or map them again with correct credentials - windows gui don't clarifies error and "net use" from windows cmd console gives vague "error 59"

I have found, that this issue could be completely solved by calling File Services->SMB->Advanced Settings->Clear SMB Cache, and, after that, every registered LDAP user could continue to use existing shared folders or map new ones without errors.

It seems, that Synology NAS starts SMB service before docker (with AzureAD-LDAP container) so in 'cold' NAS start SMB isn't aware about any LDAP users and groups. Could we somehow change order of Synology services initialization (to start Docker before SMB), or may be there is an option to call "Clear SMB Cache" from AzureAD-LDAP-wrapper, when it is started?

**Comment by ahaenggli** [comment]
No problem at all, I'm happy if it works now :)
Unfortunately, I don't know a solution for the "new" glitch either. But I've already had it. In my case, however, it does not occur with all users. It probably depends on whether the network drive was accessible during the restart of the NAS. So far I have been able to solve the problem by restarting only the affected Windows machine.

**Comment by jmeile** [comment]
I know this issue is closed, but I would like to share another solution. My IT partner got this solved with a scheduled task, here the parameters:

- User: root
- Event: Boot-up
- user-defined script: 
`systemctl restart pkg-synosamba-smbd`

This solved our problems with the share not been connected each time that the Synology was rebooted. You may also put a delay if the task isn't working:
`sleep 60`
