### ISSUE TITLE
Publish ARM container on Docker Hub

### ISSUE THREAD

**Issue by maxilampert** [ahaenggli/AzureAD-LDAP-wrapper#38]
Hi,

is it possible to publish the container to Docker Hub for linux/arm64/v8 so it can be run on RPIs as I run a K8s cluster on my RPIs and the amd64 build is not running on those?

**Comment by ahaenggli** [comment]
Hi. I have never tried to build a multiarch image before, but I will give it a try. 
Would you be willing to test the new docker tag "multiarch-test-latest"? If it works, I'll publish all versions as multiarch in the future.

**Comment by ahaenggli** [comment]
Multiarch builds will be published with the next version.

**Comment by maxilampert** [comment]
Sorry for not responding to the question. I tested the image and it worked fine for me.
