### ISSUE TITLE
Usernames are case sensitive

### ISSUE THREAD

**Issue by rvw83** [ahaenggli/AzureAD-LDAP-wrapper#40]
is it possible to disable case sensitivity of usernames ?

e.g when i login with username@mydomain.com , i cant login 
when i login with Username@mydomain.com, i can login.

this affects both with the first login ( web interface of synology ) as accessing a SMB share.

**Comment by ahaenggli** [comment]
User names are converted to lower case in the queries, so there should be no distinction between upper and lower case...

What version of DSM are you using? 
Which version of the wrapper is running? (there should be a message at startup). 
Do you see any information in the log entries? If not, you can temporarily set the `LDAP_DEBUG` environment variable to true and try again - now there should be some entries in the log.

**Comment by ahaenggli** [comment]
Hey :) I found a way to reproduce the issue. The fix is available in the dev tag and will be released with the next version.
