### ISSUE TITLE
Multifactor authentication and Wrapper

### ISSUE THREAD

**Issue by IanICTSG** [ahaenggli/AzureAD-LDAP-wrapper#44]
Unable to login users using the Wrapper with M365 as MFA is required, what could be a workaround for this?

**Comment by ahaenggli** [comment]
Did you read and follow the [FAQ](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/blob/main/FAQ.md#does-it-support-mfa-multi-factor-authentication)?
