### ISSUE TITLE
Samba and Freeradius support

### ISSUE THREAD

**Issue by DreydenGys** [ahaenggli/AzureAD-LDAP-wrapper#5]
We are trying to replace our old legacy ldap with a new one using Azure AD. As we are trying to avoid the Azure AD Domain Service solution we found your project. 
So we are actually trying to recreate our infrastructure using your project in a test environment. However we can't actually make it work and we are wondering if it's because of a misconfiguration in our side or just we're not supposed to use this project with Samba or Freeradius. Also we are actually able to obtain data using ldapsearch and also a Synology DSM VM.
If you need some logs or sample of configs files just, I can send you some.

**Comment by DreydenGys** [comment]
See pull request: #6

**Comment by ahaenggli** [comment]
I didnt try to connect samba or freeradius, so I'm not a big help with this. But your PR is merged in the main branch :)
I planed to add an entry point to allow an easier schema modification later this weekend - i'll include your fix with my addition in the next release.
Does samba/freeradius already work with #6 or does it need more?

**Comment by DreydenGys** [comment]
We're are still working on the integration of ldap and samba. For now it's still a work in progress.
