### ISSUE TITLE
Nested groups?

### ISSUE THREAD

**Issue by noque-lind** [ahaenggli/AzureAD-LDAP-wrapper#51]
Hi there,

I'm loving this wrapper. Thank you for your work.

One question: Is nested AAD groups supposed to work? As an example I have a groups called SG - ALL containing other groups that contains members. However it does not seem like the LDAP wrapper supports this? Could you let me know if that it expected or not?

**Comment by ahaenggli** [comment]
It looks like adding groups as a member of groups is enough for a Synology NAS. I have added a first version under the docker tag 2.0-dev. Feel free to try it out :)
