### ISSUE TITLE
How to fiter ?

### ISSUE THREAD

**Issue by yuhongwei380** [ahaenggli/AzureAD-LDAP-wrapper#52]
I try to filter my user   from azure ad; just like `userType eq 'Member',accountEnabled eq 'true' `or  only `accountEnabled eq 'true' `  ，it does not work ! I want to know how to filter user ,because i want to move someone that azure account is blocked .

I also try to use radius to access ldap, but it seems that I can't get users. I can't use azure user to log in Synology nas !

**Comment by ahaenggli** [comment]
When an account is locked, the user cannot log in - even if it is synchronized. What exactly is not working? Is there an error at startup? Did you follow the [installation](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/)? On which step are you stuck?

**Comment by yuhongwei380** [comment]
I followed the steps to the sixth step. I can get users from azure ad, although some users have been blocked. Then I want to use these users to log in to my Synology NAS, but it doesn't work. I want to know where I need to configure it?

**Comment by yuhongwei380** [comment]
Then I would like to ask whether my user filtering is feasible. I pass `accountEnabled eq true` to filter the account is enabled？I do it but it does not work!

**Comment by ahaenggli** [comment]
filter
Your filter looks correct to me. You can either set `GRAPH_FILTER_USERS` to only `accountEnabled eq true` or use both criterias using AND as separator: `userType eq 'Member' AND accountEnabled eq true`
Why do you think, it does not work? What would you expect where and what do you get instead? 

log in 
If the use can't login, check the access log from synology and the log of your docker container. 

permissions
Double click on a user or a group, there you can view and set permissions. For example the group ldap-user has permission to log into the DSM:
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/23347180/3c14e0d6-e42a-4e14-92a3-f8aba0760b39)
User adriano is in the group ldap-users and inherited the permission from this group:
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/23347180/75c44657-ae81-4b6e-b8dd-8ed46539f613)

**Comment by yuhongwei380** [comment]
I given the permissions of DSM , the access for usr and group  . But I can't  use the  user to login the synology web .

**Comment by ahaenggli** [comment]
Did you check the logs?

**Comment by ahaenggli** [comment]
Did you maybe write `accountEnabled eq 'true'` instead of `accountEnabled eq true`  (without ' )?

**Comment by yuhongwei380** [comment]
> 
Of course, I've tried it before without the symbol ( ' ) ,it does't  filter what i want .

**Comment by yuhongwei380** [comment]
> Did you maybe write `accountEnabled eq 'true'` instead of `accountEnabled eq true` (without ' )?

May I ask how you changed the ldap group to ldap-user, there is no user group in my Microsoft azure ad.

**Comment by ahaenggli** [comment]
> > 
> 
> Of course, I've tried it before without the symbol ( ' ) ,it does't filter what i want .

What does it do and what do you want? I'm sorry, but with this little information I can't help you.

> > 
> 
> May I ask how you changed the ldap group to ldap-user, there is no user group in my Microsoft azure ad.

You can add as many groups as you want in Microsoft Azure AD.

**Comment by yuhongwei380** [comment]
> > > 
> > 
> > 
> > Of course, I've tried it before without the symbol ( ' ) ,it does't filter what i want .
> 
> What does it do and what do you want? I'm sorry, but with this little information I can't help you.
> 
> > > 
> > 
> > 
> > May I ask how you changed the ldap group to ldap-user, there is no user group in my Microsoft azure ad.
> 
> You can add as many groups as you want in Microsoft Azure AD.

I mean when I joined ldap, I don't know why there is a default group of users in the ldap group, but this group is not actually in my azure ad group.

**Comment by noque-lind** [comment]
This is how I filter groups - I think maybe some queries requires this form of input
<img width="611" alt="Skærmbillede 2023-05-16 kl  12 31 22" src="https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/58248091/fe3835a8-296e-4c86-ac63-b44e63f9217d">

**Comment by ahaenggli** [comment]
`accountEnabled eq true` works. I have tested it locally. If it doesn't work for you, I need the log entries to see the error.
In the last provided printscreen `accountEnabled eq 'true'` was written - which does not work because of the '. 
the default group "Users" is added by the wrapper so that there is at least one group for each user. Without at least 1 group, Synology will not run. You cannot change this behavior.

Before customizing the settings, try to install it according to the instructions and test the user login. Only if everything works, I recommend to work with the filters. This way you can exclude other incorrect settings when troubleshooting.

**Comment by yuhongwei380** [comment]
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/efb4d2d4-da49-40ef-9577-7d2fa43e9739)
Maybe I have a problem with my idea. I want to use this project to connect to azure-ad, so that Synology nas will have azure ad users, and then I will enable the radius service, so that the enterprise network can use 802.1X authentication service. At present, I can get the users of azure ad, but I can't use these users to log in to DSM. I don't know where my problem lies. I also set the permission of DSM .

**Comment by ahaenggli** [comment]
I've never tried the Radius service, so I don't know if that works.
If you get the users on your NAS, that's a good start! :) Now you can temporarily set `LDAP_DEBUG` to `true`. Then try to log in with one of your users. You should see the login attempt in the log of your Docker container. Please post the full log output of the login attempt (of course you can anonymize the mail/username).

**Comment by yuhongwei380** [comment]
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/36dc0092-0ab0-4004-885b-e2052badd9c3)
I am now trying to log in to Synology nas as a user in azure ad. The screenshot above is the log in docker. Please check~

**Comment by ahaenggli** [comment]
Do you perhaps have MFA (multi-factor authentication) enabled in your tenant?

**Comment by yuhongwei380** [comment]
> Do you perhaps have MFA (multi-factor authentication) enabled in your tenant?

yeap，for safe，we enabled the  MFA

**Comment by ahaenggli** [comment]
LDAP does not support the query of an additional input field for the second factor. So there is no way to implement MFA with the wrapper. This is the reason why your logins fail. Your only option would be to [ignore/bypass MFA as described here](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/configuration/bypass-mfa/) by setting `GRAPH_IGNORE_MFA_ERRORS` to `true`.

**Comment by yuhongwei380** [comment]
My Microsoft account can access the dsm and access the radius server. I will test other user account

**Comment by yuhongwei380** [comment]
> eq(accountEnabled, true)

![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/0c3b52be-17c7-411f-b735-28bbacbc1b5c)
Microsoft officially describes this usage

**Comment by yuhongwei380** [comment]
> This is how I filter groups - I think maybe some queries requires this form of input <img alt="Skærmbillede 2023-05-16 kl 12 31 22" width="611" src="https://user-images.githubusercontent.com/58248091/238616623-fe3835a8-296e-4c86-ac63-b44e63f9217d.png">
> 
> so maybe try: eq(accountEnabled, true)
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/50a49599-b6be-4616-8006-39d5ff5a4ddc)

Microsoft officially describes this usage

**Comment by yuhongwei380** [comment]
> LDAP does not support the query of an additional input field for the second factor. So there is no way to implement MFA with the wrapper. This is the reason why your logins fail. Your only option would be to [ignore/bypass MFA as described here](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/configuration/bypass-mfa/) by setting `GRAPH_IGNORE_MFA_ERRORS` to `true`.

How do I clear the ldap cache because the information in my ldap-group is larger than the data I filtered (I used the default filter Security group = true)

**Comment by ahaenggli** [comment]
The fastest way to clear the cache is to delete the contents of the mapped /app/.cache folder (e.g. /docker/ldap/ on your NAS). If you have not mapped the folder, simply stop the container, reset it and start it again.

**Comment by yuhongwei380** [comment]
> The fastest way to clear the cache is to delete the contents of the mapped /app/.cache folder (e.g. /docker/ldap/ on your NAS). If you have not mapped the folder, simply stop the container, reset it and start it again.

Your advice was very helpful,when I cleaned up all files in /app/.cache and reset the container, my policy that  fitler users and groups are worked . Thanks so much !

**Comment by yuhongwei380** [comment]
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/98c0f4ba-fb8d-4cfb-9a76-2ac1ccfdae32)
