### ISSUE TITLE
LDAP-wrapper   connect   freeradius

### ISSUE THREAD

**Issue by yuhongwei380** [ahaenggli/AzureAD-LDAP-wrapper#53]
I saw the previous issue and would like to ask if I should treat ldap-wrapper as an OPENldap server. Then I go to freeradius and follow the configuration of the openldap server I am connected to? I have tried freeradius access but am having problems pulling up the authentication side.

**Comment by yuhongwei380** [comment]
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/ce0ba185-0b14-4dd4-89ca-dcdccf839ef7)

**Comment by ahaenggli** [comment]
I do not know freeradius at all. The error seems to say that the password attribute was not found. Can freeradius use the sambaNTPassword attribute?
Did you bind freeradius to the ldap wrapper with a binduser or one that actually exists? You need to use a binduser so it has permission to read the password attribute for all users.

**Comment by yuhongwei380** [comment]
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/0361ab62-e2bc-41a8-ad57-3e9aa829b3ae)
I think there is something wrong with my configuration here, but I don't know the correct way to do it ;

**Comment by yuhongwei380** [comment]
freeradius can  use the sambaNTPassword ,I will try  do this later . thank you

**Comment by yuhongwei380** [comment]
> binduser

binduser="admin-user |  password "   by this ?

**Comment by ahaenggli** [comment]
Exactly. If the user is defined in the ldap-wrapper as follows:
```
LDAP_BINDUSER=admin-user|secret-password
```

You should be able to set it in freeradius like this:
```
ldap {
...
   identity = 'uid=admin-user'
   password = 'secret-password'
...
```

**Comment by yuhongwei380** [comment]
> Exactly. If the user is defined in the ldap-wrapper as follows:
> 
> ```
> LDAP_BINDUSER=admin-user|secret-password
> ```
> 
> You should be able to set it in freeradius like this:
> 
> ```
> ldap {
> ...
>    identity = 'uid=admin-user'
>    password = 'secret-password'
> ...
> ```
when i use LDAP_BINDUSER  ；and freeradius -X to test， i  see it in the logs of docker image that is ldap-wrapper
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/658a3102-b644-4fb0-bc0b-d586b57ec2a5)

**Comment by yuhongwei380** [comment]
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/fa62cf93-8bd5-4c94-9015-2b121633732e)
I used freeradius -X debug mode again and then found that radius was not getting data from ldap
My azure-ldap logs are as follows
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/8ec2150d-524e-46be-b8d9-251baebcd851)
