### ISSUE TITLE
Synology LDAP join issue

### ISSUE THREAD

**Issue by vanderpunk** [ahaenggli/AzureAD-LDAP-wrapper#54]
Setup your wrapper on a server using podman-compose. Issue joining the LDAP directory from the Synology NAS, once it get's to Check profile it fails. Was wondering if you've seen this issue or had any suggestions.
Thanks,
Vanderpunk

![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/69319211/c697e6b8-647b-40d5-a005-c3415ebb0121)

**Comment by ahaenggli** [comment]
Can you check the docker log? It looks like it didn't retrieve any users or groups from Azure.

**Comment by vanderpunk** [comment]
That was indeed the issue. Thank you.
