### ISSUE TITLE
AAD invited users

### ISSUE THREAD

**Issue by oleksandrmeleshchuk-epm** [ahaenggli/AzureAD-LDAP-wrapper#61]
Is it possible to have AAD invited users in the LDAP-wrapper?

Let's say there are:
1. AAD tenant;
2. current tenant users (working fine)
3. invited users (member/guest type)

As of right now - users are imported into the LDAP-wrapper but while try to fetch any data from (using ldap search) - I'm getting no such object error.

**Comment by ahaenggli** [comment]
It is important to note that the LDAP-wrapper only partially supports invited users from Azure Active Directory (AAD). Invited users must be from another AAD tenant. Personal Microsoft Accounts, such as outlook.com, hotmail.com, or live.com, are not compatible with the LDAP-wrapper due to Microsoft's restrictions. Similarly, guests without an AAD are also not supported for the same reason.

If you encounter issues with these "failing" users, they should be logged when you start the wrapper. However, if you have an invited user whose invitation has been accepted, the user will be synchronized with the LDAP-wrapper. It is worth mentioning that invited users will retain their original domain as part of their name in the LDAP entry to avoid duplicate entries.

For example, if your domain is `domain.tld` and you invited `sample@example.com`, the corresponding LDAP entry for this user would be `uid=sample_example.com,cn=users,dc=domain,dc=tld`.

**Comment by oleksandrmeleshchuk-epm** [comment]
thx for a promt reply.
1. Invited user is from another AAD tenant (not live.com, not a guest without AAD)
2. Error message (screenshot attached)
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/df16f165-87d1-4d62-be8b-2fb5d41cc20c)
2.1. AAD sign in log 
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/edbcdfac-a7e3-478b-ba83-f6b16c5363df)
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/32338402-78e8-404a-9bb0-73b7077b14b2)
3. User does exist in the LDAP DB
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/2f21aab4-6740-4d87-9466-e4d3c589de97)
 but as you can see from the screenshot attribute sambeNTPPassword is equal xxxxxxxxxxxxxxxxxxx and sambaPwdLastSet equal 0, rather than value as for a user which was created inside of the original AAD tenant (screenshot below
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/278261c7-d13b-4434-8310-105732fbfd80)
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/6b6ee12a-de52-4924-acdf-d5d1255e64e6)

Regarding userPrincipal attribute change:
1. While users are invited they are created with an #ext# prefix in the UPN
1.1. LDAP-wrapper importing user with this prefix, which afterwards causing LDAP client not to be able to read properties of this users (most probably due to some issue with the special symbol processing, I'm using LDAP Admin)

As a optional solution - UPN changing (removing prefix) is fixing this, without breaking further user sync from the AAD.

**Comment by oleksandrmeleshchuk-epm** [comment]
Hi,
1. I'm trying to test login using invited as member to the AAD user, username attribute used for the username is: mail(as I was mentioning previously - auth does work for the AAD users, but not for invited users)
2. I'm using latest docker image 
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/b912c87d-5d8d-4c02-bd7d-c6ed084fb5c7)
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/59a30209-465e-41d7-a0dd-bafe694ba7c2).
3. Yes, invited AAD user record were created in the azure.json and users.json files.
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/0dedb1fa-6929-437b-bdee-747e3e29584a)
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/90abd487-fa52-41bd-80f1-514b46e1bd38)

**Comment by ahaenggli** [comment]
Thank you very much for the details. Your user is not recognized as external (`AzureADuserExternal` is 0 instead of 1). Based on your users.json entry, the `userType` seems to be `Member` while I would expect `Guest`...
I will improve the detection of external users with the next version.

**Comment by ahaenggli** [comment]
An improved version is now in the Docker DEV tag. Feel free to try it out :)

**Comment by oleksandrmeleshchuk-epm** [comment]
I've just tried using DEV tag docker image and result's are:
1. invited User with a Member type, after AAD has been created - working fine (auth successfull)
2. User created withing original AAD - working fine
3. User (from another AAD) which was used to create original AAD - doesn't work, error message from the user sync process:
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/20fcb246-cca0-46c0-8149-01b9614a5cd1)
3.1. User auth attempt error message:
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/7c525767-476d-44a5-a385-e098f9355c68)
3.2. This is how users in the AAD look's like
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/57523242/3c2bec1b-29b1-4907-90ce-38c5b8ce786a)

User was able to auth only after:
1. removing mentioned above user (the one who've created original AAD) from it
2. inviting user again to the AAD
3. changing status to Member
4. removing files from the data/* folder
5. docker container restart

So my init question is now resolved:)

Thank u

**Comment by noque-lind** [comment]
Sorry for revisiting this case. For me guest users works with the initial login (Synology DSM). However i have not been able to make SMB authenticating work for these guest users when using their original UPN. 

I can log these users in when using the guest upn, like the attached screenshot.

Is there anyway to work around this?

<img width="596" alt="Skærmbillede 2024-01-05 kl  10 54 45" src="https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/58248091/5278127e-07fc-460d-8cf6-0562982ea69b">

**Comment by ahaenggli** [comment]
Samba (or maybe Windows OS, I'm not sure here) cuts off the domain. If you enter `alice@external.com` the LDAP-wrapper receives only `alice`. As a workaround - assuming you're using the latest version - you could try replace the @ with an underline _  in SMB auth for guest users. So by using `alice_external.com` as username it should send everything to the wrapper - but only for guest users.
