### ISSUE TITLE
container not starting anymore

### ISSUE THREAD

**Issue by CTroessaert** [ahaenggli/AzureAD-LDAP-wrapper#68]
Hello,

I'm running the container on a Synology DS1621+ running DSM 7.2.1 update 1 with Node.js v18

I have the following log of the container that does not start anymore:

2023/11/24 13:50:57	stdout	Node.js v18.17.0
2023/11/24 13:50:57	stdout	
2023/11/24 13:50:57	stdout	    at [90m/app/[39mindex.js:12:28
2023/11/24 13:50:57	stdout	[90m    at require (node:internal/modules/cjs/helpers:110:18)[39m
2023/11/24 13:50:57	stdout	[90m    at Module.require (node:internal/modules/cjs/loader:1143:19)[39m
2023/11/24 13:50:57	stdout	[90m    at Module._load (node:internal/modules/cjs/loader:960:12)[39m
2023/11/24 13:50:57	stdout	[90m    at Module.load (node:internal/modules/cjs/loader:1119:32)[39m
2023/11/24 13:50:57	stdout	[90m    at Module._extensions..js (node:internal/modules/cjs/loader:1310:10)[39m
2023/11/24 13:50:57	stdout	[90m    at Module._compile (node:internal/modules/cjs/loader:1256:14)[39m
2023/11/24 13:50:57	stdout	    at Object.<anonymous> [90m(/app/[39msrc/server.js:24:17[90m)[39m
2023/11/24 13:50:57	stdout	    at helper.ReadJSONfile [90m(/app/[39msrc/helper.js:63:22[90m)[39m
2023/11/24 13:50:57	stdout	    at JSON.parse (<anonymous>)
2023/11/24 13:50:57	stdout	SyntaxError: Unexpected end of JSON input
2023/11/24 13:50:57	stdout	
2023/11/24 13:50:57	stdout	    "entry
2023/11/24 13:50:57	stdout	undefined:12043

Any idea what to do ? thanks !

**Comment by ahaenggli** [comment]
According to the error, it cannot load the json file with the existing users. Can you empty the mapped directory completely?
So it should recreate everything as at the first start.
