### ISSUE TITLE
Jira integration

### ISSUE THREAD

**Issue by vanderpunk** [ahaenggli/AzureAD-LDAP-wrapper#70]
Jira offers LDAP as a User Directory. I'm trying to use my azuread-ldap-wrapper as the source. Jira LDAP Directory Type has Microsoft Active Directory, Apache Directory Server (1.0.x and 1.5.x), Apple Open Directory, FedoraDS, Generic Directory Server, Novell eDirectory Server, OpenDS, OpenLDAP, Generic Posix/RFC2307, and Sun Directory Server Enterprise Edition.

Are any of these compatible with AzureAD-LDAP-wrapper?
Do you have any suggestions or recommendations for using AzureAD-LDAP-wrapper as the LDAP Directory for Atlassian products?

**Comment by ahaenggli** [comment]
I have never tried it. Given the options, you might try OpenLDAP or Generic Posix/RFC2307. The others seem too specific to me.

**Comment by yuhongwei380** [comment]
> Jira offers LDAP as a User Directory. I'm trying to use my azuread-ldap-wrapper as the source. Jira LDAP Directory Type has Microsoft Active Directory, Apache Directory Server (1.0.x and 1.5.x), Apple Open Directory, FedoraDS, Generic Directory Server, Novell eDirectory Server, OpenDS, OpenLDAP, Generic Posix/RFC2307, and Sun Directory Server Enterprise Edition.
> 
> Are any of these compatible with AzureAD-LDAP-wrapper? Do you have any suggestions or recommendations for using AzureAD-LDAP-wrapper as the LDAP Directory for Atlassian products?

You can use OIDC or Saml  to bind jira to azure, it is supported ~
