### ISSUE TITLE
Ldaps

### ISSUE THREAD

**Issue by dany85free** [ahaenggli/AzureAD-LDAP-wrapper#71]
Can I use LDAP over TLS (STARTTLS) instead of LDAP (without encryption)?

**Comment by ahaenggli** [comment]
No, as mentioned in the [docs](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/troubleshooting/#can-i-use-ldap-over-tls-starttls-instead-of-ldap-with-no-encryption). Unfortunately, the underlying ldapjs server does not support this: https://github.com/ldapjs/node-ldapjs/issues/663
However, the use of LDAP over SSL would work.

**Comment by dany85free** [comment]
Thanks, I'll try LDAP over SSL. What are the names of the variables to configure in .env?

**Comment by dany85free** [comment]
Thanks, I hadn't seen the page
