### ISSUE TITLE
Username abbreviation

### ISSUE THREAD

**Issue by yuhongwei380** [ahaenggli/AzureAD-LDAP-wrapper#75]
I created ldap according to this project, but now the ldap user contains a domain name, such as a.b@test.com. I hope that the domain name will be automatically matched when logging in, so that I only need to enter a.b. Is there a way to do this?

**Comment by ahaenggli** [comment]
Depending on the system you connect, all 3 variants may work:
- username only
- username@original.domain
- username@test.com

I personally find it easiest to use the original domain, which is why I also use this for the ldap server and not, for example, test.com.

**Comment by yuhongwei380** [comment]
OK , I will try it  again by username only ;

**Comment by yuhongwei380** [comment]
I had test , it is work, my error is i have a same user ; i change the principle name ;
