### ISSUE TITLE
question on LDAP queries on users.json

### ISSUE THREAD

**Issue by letitfly** [ahaenggli/AzureAD-LDAP-wrapper#78]
For my task, I need to access one of the attribute "accountEnabled" stored in .cache/users.json

I can run ldap queries on stuff in .cache/azure.json, but have no idea on how to query stuff in .cache/users.json.

Anyone knows how?

**Comment by ahaenggli** [comment]
You can only query the values in azure.json. This is the file with the entire ldap database in it. You need to write and use a [customizer](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/configuration/customize-attributes/) to adjust/add values (function customizer.ModifyLDAPUser). Once the values are in the azure.json, you can query them.

**Comment by letitfly** [comment]
got it. Thank you!
