### ISSUE TITLE
Example for ldapsearch

### ISSUE THREAD

**Issue by tnagels** [ahaenggli/AzureAD-LDAP-wrapper#8]
I have the container up and running and through what shows up in the logs I can see it is connected to AzureAD.

However, I cannot seem to get ldapsearch to successfully connect. I get either "Invalid Credentials" or "Invalid DN Syntax". Could you give an example of an ldapsearch command which should work? Preferably both for a "real" Azure user and for a bind user defined in the environment variables.

**Comment by ahaenggli** [comment]
I'm usually using PowerShell - there is a sample [here](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/blob/main/schema/ldap_seacher.ps1)
For the linux ldapsearch I tried this successfully:
```
ldapsearch -x -D "uid=binduser,cn=users,dc=example,dc=com" -w password1234 \
           -H ldap://127.0.0.1 -b "cn=users,dc=example,dc=com" \
           -s sub 'uid=*'
```

`binduser` can either be a real Azure-User oder the one from ENV variables.
