### ISSUE TITLE
Question for ldap

### ISSUE THREAD

**Issue by yuhongwei380** [ahaenggli/AzureAD-LDAP-wrapper#82]
I try to  use another app to connect this ldap wrapper;   It  noticed i need to fill  with the cn,ou in the base DN, what should i need to fill ; for example ,my base dn is  test.com , the bind user is test ,the password is test .

**Comment by ahaenggli** [comment]
It depends. There are some [usage examples](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/usage/), maybe you find what you want there?

**Comment by yuhongwei380** [comment]
![image](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/assets/44333391/bcf22089-edcb-4deb-95d3-07f64ac0ee0f)
the  app  like this ; i am confuse ; i fill it but it reported errors

**Comment by yuhongwei380** [comment]
don't find about for the ou in this[ site](https://ahaenggli.github.io/AzureAD-LDAP-wrapper/usage/portainer/#ldap-configuration)

**Comment by ahaenggli** [comment]
The wrapper does not create ou entries. Your application probably uses the term `user ou` for `base dn`. Therefore try `cn=users,dc=domain,dc=tl`.

**Comment by yuhongwei380** [comment]
when i use the ldap3 to connect  ldap-swapper; it  noticed that ldap3.core.exceptions.LDAPBindError: automatic bind not successful - invalidCredentials  ; 

I also use ldapsearch to  verify this ;also error; 
```
[vetest@localhost ~]$ ldapsearch -x -H ldap://192.168.8.199 -D "cn=admin,dc=test,dc=com" -w "Test123." -b "dc=test,dc=com"
ldap_bind: Invalid credentials (49)
```

**Comment by ahaenggli** [comment]
try 
```bash
ldapsearch -x -H ldap://192.168.8.199 -D "uid=admin" -w "Test123." -b "dc=test,dc=com"
```

**Comment by yuhongwei380** [comment]
> try
> 
> ```shell
> ldapsearch -x -H ldap://192.168.8.199 -D "uid=admin" -w "Test123." -b "dc=test,dc=com"
> ```

yeap; it work success !
