### ISSUE TITLE
[Question] Imbricated groups

### ISSUE THREAD

**Issue by Oneloutre** [ahaenggli/AzureAD-LDAP-wrapper#84]
Hello !

First of all, congrats for your work, it looks amazing.

I have a question.
What will happen if I have a lot of groups imbricated ? (I think it's called nested groups in ldap...) I have a few security groups with users part of different groups at once, and I'd like to keep the structure in my LDAP. Do you think that it will work ?

Regards,

**Comment by ahaenggli** [comment]
You will have to try it out. It probably depends on the server that uses the ldap wrapper as its user database.

If a group is member of group, it is also [added as a member](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/blob/f7716b34c3c9a16e0065d977a222a610f6b7f28a/src/database.js#L506) of the group in the ldap-wrapper.
