### ISSUE TITLE
Cannot sync

### ISSUE THREAD

**Issue by gianacta** [ahaenggli/AzureAD-LDAP-wrapper#90]
Hi,
I am trying to sync Entra ID groups and users to provide them through LDAP. The container seems to successfully syncs all groups, but when it starts syncing users, I encounter the following error:
`database.js mergeAzureEntries TypeError: Cannot read properties of undefined (reading 'entryDN')`

Thanks
Gianluca

**Comment by gianacta** [comment]
I've tried just with LDAP_DOMAIN (example.com) and also with both LDAP_DOMAIN (example.com) and LDAP_BASEDN (dc=example,dc=com) but nothing changed.

**Comment by gianacta** [comment]
I would like to sync only users, might that make sense?

**Comment by gianacta** [comment]
Maybe i found the problem, i've got some groups that contains "/", how can i exclude them from the import?

**Comment by ahaenggli** [comment]
Special characters are replaced by “-”, so there should be no problems with slashes. 
Do you have other errors/warnings or just this one entry in your log?
`database.js mergeAzureEntries TypeError: Cannot read properties of undefined (reading 'entryDN')`

If you really want no groups to be synchronized, you can set your environment variable for the group filter to something like
`GRAPH_FILTER_GROUPS=displayName eq 'none'`
This way, only the group with the specific name “none” would be synchronized (which does not exist).
