### ISSUE TITLE
Error When Try To Authenticate To a Share with a Entra ID Joined Device

### ISSUE THREAD

**Issue by NicholasK516** [ahaenggli/AzureAD-LDAP-wrapper#92]
When mapping one of the network shares I get the error "System cannot contact a domain controller to service the authentication request. Please try again later."

- This Device is Entra Joined and Managed By Microsoft Intune
- The Device is able to ping the Synlogy
- We Do Not Have an onsite Active Directory
- Only two devices are having this issue at the moment 
- One of them has windows hello enabled the other does not

**Comment by ahaenggli** [comment]
The error usually occurs if you do not connect via user name and password. For azure ad joined devices, Windows suggests logging in via PIN or the currently logged in user (similar to SSO). Neither works, as the wrapper cannot know this information.

**Comment by NicholasK516** [comment]
On some machines Windows just automatically passed the credentials and it worked. Those machines had Windows Hello enabled as well. So typical then users would need to put in their Network credentials as the pass through authentication should not work? Is there anyway to make it work properly?

**Comment by ahaenggli** [comment]
you could try removing the current network credentials from the windows credential manager and then add the shares by console to make sure the correct username/password is used, like in [issue #7](https://github.com/ahaenggli/AzureAD-LDAP-wrapper/issues/7#issuecomment-886032824)
