### ISSUE TITLE
Samba NT-Password is displayed in plain text for others Users

### ISSUE THREAD

**Issue by CHEETX** [ahaenggli/AzureAD-LDAP-wrapper#95]
Hi,

if I'm not mistaken, the azure.json file, stored in the docker folder, is supposed to show my personal samba NT Password in plain text but showing XXXX for the others users. In my case, I can see all the passwords of the users who logged in clear text. Am I missing something?

thx a lot

Cheet

**Comment by ahaenggli** [comment]
You are mixing up LDAP queries and the file. With direct access to the file, you can see everything. 
XXXX values are only delivered in a response if you send an LDAP query to the server.

**Comment by CHEETX** [comment]
Thx,
When you say " With direct access to the file", are we agree "direct access" is the right way to make samba work properly. ( everybody must have access anonymously to this file )
Cheey

**Comment by ahaenggli** [comment]
Nope. No 3rd party does access this file directly. Did you read the manual?

**Comment by CHEETX** [comment]
"Restrict access through a firewall. Do NOT allow everyone in your network access to the LDAP-wrapper.
Only your (local hosted) applications or your NAS should have access."

Got It
thx!
