### ISSUE TITLE
Check server Schema hang

### ISSUE THREAD

**Issue by waybackrider** [ahaenggli/AzureAD-LDAP-wrapper#96]
Hi,
I'm trying to join the wrapper to Synology NAS according to your Doc (https://ahaenggli.github.io/AzureAD-LDAP-wrapper/installation/use-synology-nas/), but cannot get beyond "Check Server schema".

![ldapwpr2png](https://github.com/user-attachments/assets/bc2096d7-ee80-44bb-b8a4-f2a892500e73)

Have also enabled Debug:

![ldapwpr1](https://github.com/user-attachments/assets/5cbce89c-eba7-4b43-bc14-391488b29385)

In the Log i can also see all the Usernames in my Domain, so Connection to Entra seems to be estabilsted.
Any Ideas?

Thanks!

**Comment by ahaenggli** [comment]
If you click on the gray “Details” button (first printscreen), is there an option to skip the check?

**Comment by waybackrider** [comment]
Thanks! Now it passes, have not thought it is an Requirement to skip the Warning ("you _can_ ignore it and skip the warning").
