### ISSUE TITLE
Add Devices

### ISSUE THREAD

**Issue by cbahern** [ahaenggli/AzureAD-LDAP-wrapper#97]
Is it possible to add Devices from Entra ID to the returned objects?  I have a use case for using machine based certificate authentication for wireless access.  The current implementation does not return devices, and returns and empty member set for an Entra ID group that contains devices as members.

**Comment by ahaenggli** [comment]
This is not possible with the endpoints used. MS Graph uses different endpoints for devices and their group memberships.

**Comment by cbahern** [comment]
OK, thanks for looking and the explanation.

**Comment by cbahern** [comment]
I was able to add this functionality in a fork.  Here are the diffs:  https://github.com/ahaenggli/AzureAD-LDAP-wrapper/compare/main...cbahern:AzureAD-LDAP-wrapper:main#diff-23821ae067a9c7dfb6227774aefb39fa3951a5874ea953b9401dfc80175c026cR37-R61

Let me know if you want me to create a pull request.

**Comment by ahaenggli** [comment]
@cbahern a pull request would be great :)

**Comment by cbahern** [comment]
This is my first pull request, so hopefully I did it correctly.  Obviously, the Docker changes were made to run and test in my own environment and can be ignored.
________________________________
